name: ASP.NET Core backend and Ts UI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: npm install, build, and test
      run: |
        npm install
        npm run release --if-present
        npm run test --if-present
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
