name: ASP.NET Core backend and Ts UI

on: [push]

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get master code
    - uses: actions/checkout@master
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run release --if-present
        npm run test --if-present
        
    - name: Setup .NET Core
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
